/**
 * 输电线路-运维平台后管理接口-dev环境
 * 莫图云平台
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: cloud@motutec.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 登录用户响应
 * @export
 * @interface LoginUserInfoVo
 */
interface LoginUserInfoVo {
  /**
   * 邮件
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  email?: string;
  /**
   * 主键
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  id: string;
  /**
   * 头像http地址
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  imgUrl?: string;
  /**
   * 最近一次登录时间
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  lastLoginTime?: string;
  /**
   * 锁定理由
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  lockReason?: string;
  /**
   * 锁定状态[0：未锁定、1：锁定]
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  lockState?: string;
  /**
   * 昵称
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  nickname: string;
  /**
   * 机构ID
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  orgId: string;
  /**
   * 电话
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  phone?: string;
  /**
   * 用户凭证
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  token: string;
  /**
   * 用户类型[system：系统用户、org：机构用户]
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  type: string;
  /**
   * 用户名
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  username: string;
  /**
   * 微信号
   * @type {string}
   * @memberof LoginUserInfoVo
   */
  wxNo?: string;
}

export type { LoginUserInfoVo };
