/**
 * 输电线路-运维平台后管理接口-dev环境
 * 莫图云平台
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: cloud@motutec.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 登录信息
 * @export
 * @interface LoginAo
 */
interface LoginAo {
  /**
   * 密码
   * @type {string}
   * @memberof LoginAo
   */
  password: string;
  /**
   * 账号
   * @type {string}
   * @memberof LoginAo
   */
  username: string;
}

export type { LoginAo };
